"""Two pre-filled booking payloads for the demo: one that the model considers
likely to cancel, one that it considers likely to stay. Sourced from rows in
`hotels.csv` chosen by `_pick_samples.py` (run once, output cached here)."""
from __future__ import annotations

LIKELY_CANCEL: dict = {
    "hotel": "Resort Hotel",
    "lead_time": 87,
    "arrival_date_year": 2015,
    "arrival_date_month": "October",
    "arrival_date_week_number": 40,
    "arrival_date_day_of_month": 3,
    "stays_in_weekend_nights": 0,
    "stays_in_week_nights": 1,
    "adults": 2,
    "children": 0,
    "babies": 0,
    "meal": "BB",
    "country": "PRT",
    "market_segment": "Groups",
    "distribution_channel": "TA/TO",
    "is_repeated_guest": 0,
    "previous_cancellations": 0,
    "previous_bookings_not_canceled": 0,
    "reserved_room_type": "A",
    "assigned_room_type": "A",
    "booking_changes": 0,
    "deposit_type": "Non Refund",
    "agent": 96,
    "company": None,
    "days_in_waiting_list": 0,
    "customer_type": "Transient",
    "adr": 36.05,
    "required_car_parking_spaces": 0,
    "total_of_special_requests": 0,
}

LIKELY_STAY: dict = {
    "hotel": "City Hotel",
    "lead_time": 3,
    "arrival_date_year": 2016,
    "arrival_date_month": "August",
    "arrival_date_week_number": 32,
    "arrival_date_day_of_month": 8,
    "stays_in_weekend_nights": 0,
    "stays_in_week_nights": 2,
    "adults": 2,
    "children": 1,
    "babies": 0,
    "meal": "BB",
    "country": "DEU",
    "market_segment": "Direct",
    "distribution_channel": "Direct",
    "is_repeated_guest": 1,
    "previous_cancellations": 0,
    "previous_bookings_not_canceled": 3,
    "reserved_room_type": "A",
    "assigned_room_type": "A",
    "booking_changes": 1,
    "deposit_type": "No Deposit",
    "agent": None,
    "company": None,
    "days_in_waiting_list": 0,
    "customer_type": "Transient",
    "adr": 110.0,
    "required_car_parking_spaces": 1,
    "total_of_special_requests": 2,
}
